const { KEY_ROWS } = require('../data/keyboard');
const { getDefaultSymbol, hasExplicitLevel } = require('./layout');

const toXkbKeysym = symbol => {
  if (!symbol) return 'VoidSymbol';
  const trimmed = symbol.trim();
  if (!trimmed) return 'VoidSymbol';

  if (/^[A-Za-z0-9_]+$/.test(trimmed)) {
    return trimmed;
  }

  const cp = trimmed.codePointAt(0);
  return 'U' + cp.toString(16).toUpperCase().padStart(4, '0');
};

const fromXkbKeysym = keysym => {
  const trimmed = keysym.trim();
  if (!trimmed || trimmed === 'VoidSymbol') return '';

  const unicodeMatch = trimmed.match(/^U([0-9A-Fa-f]{4,6})$/);
  if (unicodeMatch) {
    return String.fromCodePoint(parseInt(unicodeMatch[1], 16));
  }

  return trimmed;
};

const parseXkbSymbols = source => {
  const layout = {};
  const keyPattern = /key\s*<([A-Za-z0-9_]+)>\s*\{\s*\[\s*([^\]]*?)\s*\]\s*\};/g;
  let match;
  let importedCount = 0;

  while ((match = keyPattern.exec(source))) {
    const code = match[1];
    const symbols = match[2]
      .split(',')
      .map(symbol => fromXkbKeysym(symbol))
      .slice(0, 4);

    while (symbols.length < 4) {
      symbols.push(undefined);
    }

    layout[code] = symbols.map(symbol => symbol === undefined ? undefined : symbol);
    importedCount += 1;
  }

  return { layout, importedCount };
};

const createXkbSnippet = layout => {
  const lines = [
    '// Generated by xkbedit',
    'default partial alphanumeric_keys',
    'xkb_symbols "basic" {',
    '    name[Group1]= "Custom Layout";',
    ''
  ];

  KEY_ROWS.forEach(row =>
    row.forEach(key => {
      const levels = layout[key.code];
      const highestLevel = levels
        ? levels.reduce((highest, value, index) => hasExplicitLevel(value) ? index : highest, -1)
        : -1;

      if (highestLevel >= 0) {
        const symbols = Array.from({ length: highestLevel + 1 }, (_, i) => {
          const val = hasExplicitLevel(levels[i]) ? levels[i] : getDefaultSymbol(key, i);
          return toXkbKeysym(val);
        });
        lines.push(`    key <${key.code}> { [ ${symbols.join(', ')} ] };`);
      }
    })
  );

  lines.push('};');
  return lines.join('\n');
};

module.exports = {
  createXkbSnippet,
  parseXkbSymbols
};
