const { KEY_ROWS } = require('../data/keyboard');
const {
  collectExplicitSymbols,
  getDefaultSymbol,
  hasExplicitLevel,
  shouldRemoveDefault
} = require('./layout');

const EXPORT_DEFAULT_LEVELS = 2;

const toXkbKeysym = symbol => {
  if (!symbol) return 'VoidSymbol';
  const trimmed = symbol.trim();
  if (!trimmed) return 'VoidSymbol';

  if (/^[A-Za-z0-9_]+$/.test(trimmed)) {
    return trimmed;
  }

  const cp = trimmed.codePointAt(0);
  return 'U' + cp.toString(16).toUpperCase().padStart(4, '0');
};

const fromXkbKeysym = keysym => {
  const trimmed = keysym.trim();
  if (!trimmed || trimmed === 'VoidSymbol') return '';

  const unicodeMatch = trimmed.match(/^U([0-9A-Fa-f]{4,6})$/);
  if (unicodeMatch) {
    return String.fromCodePoint(parseInt(unicodeMatch[1], 16));
  }

  return trimmed;
};

const parseXkbSymbols = source => {
  const layout = {};
  const keyPattern = /key\s*<([A-Za-z0-9_]+)>\s*\{\s*\[\s*([^\]]*?)\s*\]\s*\};/g;
  let match;
  let importedCount = 0;

  while ((match = keyPattern.exec(source))) {
    const code = match[1];
    const symbols = match[2]
      .split(',')
      .map(symbol => fromXkbKeysym(symbol))
      .slice(0, 4);

    while (symbols.length < 4) {
      symbols.push(undefined);
    }

    layout[code] = symbols.map(symbol => symbol === undefined ? undefined : symbol);
    importedCount += 1;
  }

  return { layout, importedCount };
};

const getKeyboardKeys = keyRows => keyRows.flat().filter(key => key.type !== 'spacer');

const getExportLevels = (key, layout, explicitSymbols, removeUsedDefaults) => {
  const levels = layout[key.code];
  const highestExplicitLevel = levels
    ? levels.reduce((highest, value, index) => hasExplicitLevel(value) ? index : highest, -1)
    : -1;
  const levelCount = Math.max(EXPORT_DEFAULT_LEVELS, highestExplicitLevel + 1);

  return Array.from({ length: levelCount }, (_, layer) => {
    if (levels && hasExplicitLevel(levels[layer])) {
      return levels[layer];
    }

    const defaultValue = getDefaultSymbol(key, layer);
    if (shouldRemoveDefault(key, defaultValue, explicitSymbols, removeUsedDefaults)) {
      return '';
    }

    return defaultValue || '';
  });
};

const createXkbSnippet = (layout, options = {}) => {
  const removeUsedDefaults = options.removeUsedDefaults !== false;
  const keyRows = options.keyRows || KEY_ROWS;
  const explicitSymbols = collectExplicitSymbols(layout);
  const lines = [
    '// Generated by xkbedit',
    'default partial alphanumeric_keys',
    'xkb_symbols "basic" {',
    '    name[Group1]= "Custom Layout";',
    ''
  ];

  getKeyboardKeys(keyRows).forEach(key => {
    const symbols = getExportLevels(key, layout, explicitSymbols, removeUsedDefaults).map(toXkbKeysym);
    lines.push(`    key <${key.code}> { [ ${symbols.join(', ')} ] };`);
  });

  lines.push('};');
  return lines.join('\n');
};

module.exports = {
  createXkbSnippet,
  parseXkbSymbols
};
