const React = require('react');
const { createRoot } = require('react-dom/client');

const e = React.createElement;

const KEY_ROWS = [
  [
    { code: 'TLDE', label: '`' },
    { code: 'AE01', label: '1' },
    { code: 'AE02', label: '2' },
    { code: 'AE03', label: '3' },
    { code: 'AE04', label: '4' },
    { code: 'AE05', label: '5' },
    { code: 'AE06', label: '6' },
    { code: 'AE07', label: '7' },
    { code: 'AE08', label: '8' },
    { code: 'AE09', label: '9' },
    { code: 'AE10', label: '0' },
    { code: 'AE11', label: '-' },
    { code: 'AE12', label: '=' },
    { code: 'BKSP', label: 'Backspace' }
  ],
  [
    { code: 'TAB', label: 'Tab' },
    { code: 'AD01', label: 'Q' },
    { code: 'AD02', label: 'W' },
    { code: 'AD03', label: 'E' },
    { code: 'AD04', label: 'R' },
    { code: 'AD05', label: 'T' },
    { code: 'AD06', label: 'Y' },
    { code: 'AD07', label: 'U' },
    { code: 'AD08', label: 'I' },
    { code: 'AD09', label: 'O' },
    { code: 'AD10', label: 'P' },
    { code: 'AD11', label: '[' },
    { code: 'AD12', label: ']' },
    { code: 'BKSL', label: '\\' }
  ],
  [
    { code: 'CAPS', label: 'Caps' },
    { code: 'AC01', label: 'A' },
    { code: 'AC02', label: 'S' },
    { code: 'AC03', label: 'D' },
    { code: 'AC04', label: 'F' },
    { code: 'AC05', label: 'G' },
    { code: 'AC06', label: 'H' },
    { code: 'AC07', label: 'J' },
    { code: 'AC08', label: 'K' },
    { code: 'AC09', label: 'L' },
    { code: 'AC10', label: ';' },
    { code: 'AC11', label: '\'' },
    { code: 'RTRN', label: 'Enter' }
  ],
  [
    { code: 'LFSH', label: 'Shift' },
    { code: 'AB01', label: 'Z' },
    { code: 'AB02', label: 'X' },
    { code: 'AB03', label: 'C' },
    { code: 'AB04', label: 'V' },
    { code: 'AB05', label: 'B' },
    { code: 'AB06', label: 'N' },
    { code: 'AB07', label: 'M' },
    { code: 'AB08', label: ',' },
    { code: 'AB09', label: '.' },
    { code: 'AB10', label: '/' },
    { code: 'RTSH', label: 'Shift' }
  ],
  [
    { code: 'LCTL', label: 'Ctrl' },
    { code: 'LWIN', label: 'Super' },
    { code: 'LALT', label: 'Alt' },
    { code: 'SPCE', label: 'Space', legend: '[SP]', span: 6 },
    { code: 'RALT', label: 'Alt' },
    { code: 'RWIN', label: 'Menu' },
    { code: 'RCTL', label: 'Ctrl' }
  ]
];

const LAYERS = [
  { id: 0, label: 'Normal' },
  { id: 1, label: 'Shift' },
  { id: 2, label: 'AltGr' },
  { id: 3, label: 'Shift+AltGr' }
];

const US_SHIFT_SYMBOLS = {
  TLDE: '~',
  AE01: '!', AE02: '@', AE03: '#', AE04: '$', AE05: '%',
  AE06: '^', AE07: '&', AE08: '*', AE09: '(', AE10: ')',
  AE11: '_', AE12: '+',
  AD11: '{', AD12: '}', BKSL: '|',
  AC10: ':', AC11: '"',
  AB08: '<', AB09: '>', AB10: '?'
};

const buildInitialLayout = () => ({});

const toXkbKeysym = symbol => {
  if (!symbol) return 'VoidSymbol';
  const trimmed = symbol.trim();
  if (!trimmed) return 'VoidSymbol';
  // If it's alphanumeric and matches XKB naming conventions, pass through.
  if (/^[A-Za-z0-9_]+$/.test(trimmed)) {
    return trimmed;
  }
  // Otherwise, use Unicode hex (robust for symbols like ! or { which aren't valid keysym names directly)
  const cp = trimmed.codePointAt(0);
  return 'U' + cp.toString(16).toUpperCase().padStart(4, '0');
};

const getDefaultSymbol = (key, layer) => {
  // Special case for Space
  if (key.code === 'SPCE' && layer === 0) return 'space';

  // Handle Shift Layer (1) for standard US symbols
  if (layer === 1 && US_SHIFT_SYMBOLS[key.code]) {
    return US_SHIFT_SYMBOLS[key.code];
  }

  // Handle Alphabetic keys (A-Z)
  // We assume labels in KEY_ROWS are single char Uppercase (Q, W, E...)
  if (key.label.length === 1 && /[A-Za-z]/.test(key.label)) {
    if (layer === 0) return key.label.toLowerCase(); // a
    if (layer === 1) return key.label.toUpperCase(); // A
    return undefined; // Alt layers empty by default
  }

  // Handle Numeric/Symbol keys in Normal Layer
  if (layer === 0 && key.label.length === 1) {
    return key.label;
  }

  // Fallback for everything else (modifiers, function keys)
  return undefined;
};

const createXkbSnippet = layout => {
  const lines = [
    '// Generated by XKB Layout Painter',
    'default partial alphanumeric_keys',
    'xkb_symbols "basic" {',
    '    name[Group1]= "Custom Layout";',
    ''
  ];
  
  KEY_ROWS.forEach(row =>
    row.forEach(key => {
      const levels = layout[key.code];
      
      // Only output if user touched the key.
      if (levels) {
        const symbols = [0, 1, 2, 3].map(i => {
          // Use stored value if exists, otherwise fallback to default
          const val = levels[i] !== undefined ? levels[i] : getDefaultSymbol(key, i);
          return toXkbKeysym(val);
        });
        lines.push(`    key <${key.code}> { [ ${symbols.join(', ')} ] };`);
      }
    })
  );
  lines.push('};');
  return lines.join('\n');
};

const KEY_GAP = 8;

const LayerSwitcher = ({ activeLayer, onChange }) => {
  return e(
    'div',
    { className: 'layer-tabs' },
    LAYERS.map(layer =>
      e(
        'button',
        {
          key: layer.id,
          className: `layer-tab${activeLayer === layer.id ? ' layer-tab--active' : ''}`,
          onClick: () => onChange(layer.id)
        },
        layer.label
      )
    )
  );
};

const Keyboard = ({ layout, activeKey, activeLayer, onKeyClick }) =>
  e(
    'div',
    { className: 'keyboard-wrapper' },
    e(
      'div',
      { className: 'keyboard' },
      KEY_ROWS.map((row, rowIdx) =>
        e(
          'div',
          { className: 'key-row', key: rowIdx },
          row.map(key =>
            e(
              'button',
              {
                key: key.code,
                className: `key${activeKey === key.code ? ' key--active' : ''}`,
                onClick: () => onKeyClick(key),
                style: key.span
                  ? {
                      width: `calc(var(--key-size) * ${key.span} + ${(key.span - 1) * KEY_GAP}px)`,
                      flex: `0 0 calc(var(--key-size) * ${key.span} + ${
                        (key.span - 1) * KEY_GAP
                      }px)`
                    }
                  : undefined
              },
              (() => {
                const storedLevels = layout[key.code];
                const legend = key.legend || key.label;
                
                // Determine what to show on the key cap
                let display;
                let shrink = false;
                let isPlaceholder = false;

                // Value from state?
                const storedVal = storedLevels ? storedLevels[activeLayer] : undefined;

                if (storedVal !== undefined) {
                  // User explicitly set this (even if empty string)
                  display = storedVal;
                } else {
                  // Try to get a default for this layer
                  const def = getDefaultSymbol(key, activeLayer);
                  if (def !== undefined) {
                    display = def;
                    isPlaceholder = !storedLevels; // Dim if purely inferred
                  } else {
                    // No default for this layer
                    // If it's the base layer and we haven't touched the key, show the physical label (e.g. "Shift")
                    if (activeLayer === 0 && !storedLevels) {
                       display = legend;
                       shrink = legend.length > 1;
                       isPlaceholder = true;
                    } else {
                       display = '';
                    }
                  }
                }

                return e(
                  'span',
                  {
                    className: `key-symbol${shrink ? ' key-symbol--small' : ''}`,
                    style: { opacity: isPlaceholder ? 0.5 : 1 }
                  },
                  display
                );
              })(),
              e('span', { className: 'key-code' }, key.code)
            )
          )
        )
      )
    )
  );

const App = () => {
  const [layout, setLayout] = React.useState(() => buildInitialLayout());
  const [activeKey, setActiveKey] = React.useState(null);
  const [activeLayer, setActiveLayer] = React.useState(0); // 0..3

  const xkbSnippet = React.useMemo(() => createXkbSnippet(layout), [layout]);

  const handleKeyClick = key => {
    const currentLevels = layout[key.code] ? [...layout[key.code]] : [undefined, undefined, undefined, undefined];
    
    // Determine prompt default value
    let promptDefault = currentLevels[activeLayer];
    if (promptDefault === undefined) {
      promptDefault = getDefaultSymbol(key, activeLayer);
    }
    // Fallback to label if mostly generic
    if (promptDefault === undefined && activeLayer === 0) {
      promptDefault = key.label;
    }

    const layerName = LAYERS.find(l => l.id === activeLayer).label;
    
    const nextValue = window.prompt(
      `Set symbol for ${key.label} (<${key.code}>)\nLayer: ${layerName}`,
      promptDefault || ''
    );

    if (nextValue === null) return; // Cancelled

    setLayout(prev => {
      const copy = { ...prev };
      
      // Initialize if missing
      if (!copy[key.code]) {
        copy[key.code] = [undefined, undefined, undefined, undefined];
      }

      const levels = [...copy[key.code]];
      levels[activeLayer] = nextValue; // Save explicitly, even if empty string
      
      copy[key.code] = levels;
      return copy;
    });
    
    setActiveKey(key.code);
  };

  const resetLayout = () => {
    if (window.confirm('Reset the layout to the default symbols?')) {
      setLayout(buildInitialLayout());
      setActiveKey(null);
    }
  };

  const downloadSnippet = () => {
    const blob = new Blob([xkbSnippet], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = 'custom.xkb';
    anchor.click();
    setTimeout(() => URL.revokeObjectURL(url), 0);
  };

  return e(
    'div',
    { className: 'app-shell' },
    e(
      'header',
      { className: 'panel' },
      e('h1', null, 'XKB Layout Painter'),
      e(
        'p',
        { className: 'intro' }, 
        e('span', null, 'Select a layer, click a key, and assign a symbol. '),
        e('br'),
        e('span', { className: 'hint' }, 'Supports 4 levels: Normal, Shift, AltGr (Level3), Shift+AltGr (Level4).')
      ),
      e(
        'div',
        { className: 'controls' },
        e('button', { type: 'button', onClick: resetLayout }, 'Reset Layout')
      )
    ),
    e(
      'section',
      { className: 'panel' },
      e(
        'div',
        { style: { display: 'flex', alignItems: 'center', marginBottom: '12px' } },
        e('h2', { style: { marginBottom: 0 } }, 'Keyboard'),
        e('span', { className: 'layer-indicator' }, `Editing: ${LAYERS[activeLayer].label}`)
      ),
      e(LayerSwitcher, { activeLayer, onChange: setActiveLayer }),
      e(Keyboard, { layout, activeKey, activeLayer, onKeyClick: handleKeyClick })
    ),
    e(
      'section',
      { className: 'panel' },
      e('h2', null, 'xkb_symbols export'),
      e(
        'div',
        { className: 'download-actions' },
        e('button', { type: 'button', onClick: downloadSnippet }, 'Download .xkb'),
        e(
          'span',
          { className: 'hint' },
          'Paste into ~/.xkb/symbols/custom'
        )
      ),
      e('textarea', {
        className: 'snippet',
        readOnly: true,
        value: xkbSnippet,
        onFocus: evt => evt.target.select()
      })
    )
  );
};

const root = createRoot(document.getElementById('root'));
root.render(e(App));
